package main

import "fmt"

func writeModule(path string, module module) {
	fmt.Println("Writing module", module.name(), "to", path)
	lines := append(
		[]string{
			"-- Please do not edit this file.",
			"-- It was generated by https://github.com/dave4420/gen-elm-wrappers",
			"",
		},
		module.source()...,
	)
	for _, line := range lines {
		fmt.Println(line)
	}
}

func main() {
	var conf = readConfig()

	for _, module := range conf.modules {
		writeModule(conf.path, module)
	}
}
