package main

import (
	"fmt"
	"os"
	"strings"
)

func writeModule(path string, module module) error {
	fmt.Println("Writing module", module.name(), "to", path)
	lines := append(
		[]string{
			"-- Please do not edit this file.",
			"-- It was generated by https://github.com/dave4420/gen-elm-wrappers",
			"",
		},
		module.source()...,
	)
	text := strings.Join(lines, "\n") + "\n"
	return os.WriteFile(path, []byte(text), 0666)
}

func main() {
	var conf = readConfig()

	for _, module := range conf.modules {
		// DAVE: handle error from writeModule()
		writeModule(conf.path, module)
	}
}
